
nohup ./MSPA.out TKDE_MSPA_DATA/graphs/Email/Email.index TKDE_MSPA_DATA/graphs/Email/Email.gr 9  TKDE_MSPA_DATA/queryfile/Email_9.Q  5        6     TKDE_MSPA_DATA/candidates/Email_6_bet.cand TKDE_MSPA_DATA/result/Email_9_bet.Res > TKDE_MSPA_DATA/log/Email_9_6_bet.log &
nohup ./MSPA.out TKDE_MSPA_DATA/graphs/Email/Email.index TKDE_MSPA_DATA/graphs/Email/Email.gr 8  TKDE_MSPA_DATA/queryfile/Email_8.Q  5        6     TKDE_MSPA_DATA/candidates/Email_7_bet.cand TKDE_MSPA_DATA/result/Email_8_bet.Res > TKDE_MSPA_DATA/log/Email_8_6_bet.log &
nohup ./MSPA.out TKDE_MSPA_DATA/graphs/Email/Email.index TKDE_MSPA_DATA/graphs/Email/Email.gr 7  TKDE_MSPA_DATA/queryfile/Email_7.Q  5        6     TKDE_MSPA_DATA/candidates/Email_8_bet.cand TKDE_MSPA_DATA/result/Email_7_bet.Res > TKDE_MSPA_DATA/log/Email_7_6_bet.log &
nohup ./MSPA.out TKDE_MSPA_DATA/graphs/Email/Email.index TKDE_MSPA_DATA/graphs/Email/Email.gr 6  TKDE_MSPA_DATA/queryfile/Email_6.Q  5        6     TKDE_MSPA_DATA/candidates/Email_9_bet.cand TKDE_MSPA_DATA/result/Email_6_bet.Res > TKDE_MSPA_DATA/log/Email_6_6_bet.log &

nohup ./MSPA.out TKDE_MSPA_DATA/graphs/Email/Email.index TKDE_MSPA_DATA/graphs/Email/Email.gr 9  TKDE_MSPA_DATA/queryfile/Email_9.Q  5        6     TKDE_MSPA_DATA/candidates/Email_6_pcp.cand TKDE_MSPA_DATA/result/Email_9_pcp.Res > TKDE_MSPA_DATA/log/Email_9_6_pcp.log &
nohup ./MSPA.out TKDE_MSPA_DATA/graphs/Email/Email.index TKDE_MSPA_DATA/graphs/Email/Email.gr 8  TKDE_MSPA_DATA/queryfile/Email_8.Q  5        6     TKDE_MSPA_DATA/candidates/Email_7_pcp.cand TKDE_MSPA_DATA/result/Email_8_pcp.Res > TKDE_MSPA_DATA/log/Email_8_6_pcp.log &
nohup ./MSPA.out TKDE_MSPA_DATA/graphs/Email/Email.index TKDE_MSPA_DATA/graphs/Email/Email.gr 7  TKDE_MSPA_DATA/queryfile/Email_7.Q  5        6     TKDE_MSPA_DATA/candidates/Email_8_pcp.cand TKDE_MSPA_DATA/result/Email_7_pcp.Res > TKDE_MSPA_DATA/log/Email_7_6_pcp.log &
nohup ./MSPA.out TKDE_MSPA_DATA/graphs/Email/Email.index TKDE_MSPA_DATA/graphs/Email/Email.gr 6  TKDE_MSPA_DATA/queryfile/Email_6.Q  5        6     TKDE_MSPA_DATA/candidates/Email_9_pcp.cand TKDE_MSPA_DATA/result/Email_6_pcp.Res > TKDE_MSPA_DATA/log/Email_6_6_pcp.log &

nohup ./MSPA.out TKDE_MSPA_DATA/graphs/Email/Email.index TKDE_MSPA_DATA/graphs/Email/Email.gr 9  TKDE_MSPA_DATA/queryfile/Email_9.Q  5        6     TKDE_MSPA_DATA/candidates/Email_6_mst.cand TKDE_MSPA_DATA/result/Email_9_mst.Res > TKDE_MSPA_DATA/log/Email_9_6_mst.log &
nohup ./MSPA.out TKDE_MSPA_DATA/graphs/Email/Email.index TKDE_MSPA_DATA/graphs/Email/Email.gr 8  TKDE_MSPA_DATA/queryfile/Email_8.Q  5        6     TKDE_MSPA_DATA/candidates/Email_7_mst.cand TKDE_MSPA_DATA/result/Email_8_mst.Res > TKDE_MSPA_DATA/log/Email_8_6_mst.log &
nohup ./MSPA.out TKDE_MSPA_DATA/graphs/Email/Email.index TKDE_MSPA_DATA/graphs/Email/Email.gr 7  TKDE_MSPA_DATA/queryfile/Email_7.Q  5        6     TKDE_MSPA_DATA/candidates/Email_8_mst.cand TKDE_MSPA_DATA/result/Email_7_mst.Res > TKDE_MSPA_DATA/log/Email_7_6_mst.log &
nohup ./MSPA.out TKDE_MSPA_DATA/graphs/Email/Email.index TKDE_MSPA_DATA/graphs/Email/Email.gr 6  TKDE_MSPA_DATA/queryfile/Email_6.Q  5        6     TKDE_MSPA_DATA/candidates/Email_9_mst.cand TKDE_MSPA_DATA/result/Email_6_mst.Res > TKDE_MSPA_DATA/log/Email_6_6_mst.log &