
nohup ./MSPA.out TKDE_MSPA_DATA/graphs/NY-d/NY-d.index TKDE_MSPA_DATA/graphs/NY-d/NY-d.gr 9  TKDE_MSPA_DATA/queryfile/NY-d_9.Q  5        6     TKDE_MSPA_DATA/candidates/NY-d_6_bet.cand TKDE_MSPA_DATA/result/NY-d_9_bet.Res > TKDE_MSPA_DATA/log/NY-d_9_6_bet.log &
nohup ./MSPA.out TKDE_MSPA_DATA/graphs/NY-d/NY-d.index TKDE_MSPA_DATA/graphs/NY-d/NY-d.gr 8  TKDE_MSPA_DATA/queryfile/NY-d_8.Q  5        6     TKDE_MSPA_DATA/candidates/NY-d_7_bet.cand TKDE_MSPA_DATA/result/NY-d_8_bet.Res > TKDE_MSPA_DATA/log/NY-d_8_6_bet.log &
nohup ./MSPA.out TKDE_MSPA_DATA/graphs/NY-d/NY-d.index TKDE_MSPA_DATA/graphs/NY-d/NY-d.gr 7  TKDE_MSPA_DATA/queryfile/NY-d_7.Q  5        6     TKDE_MSPA_DATA/candidates/NY-d_8_bet.cand TKDE_MSPA_DATA/result/NY-d_7_bet.Res > TKDE_MSPA_DATA/log/NY-d_7_6_bet.log &
nohup ./MSPA.out TKDE_MSPA_DATA/graphs/NY-d/NY-d.index TKDE_MSPA_DATA/graphs/NY-d/NY-d.gr 6  TKDE_MSPA_DATA/queryfile/NY-d_6.Q  5        6     TKDE_MSPA_DATA/candidates/NY-d_9_bet.cand TKDE_MSPA_DATA/result/NY-d_6_bet.Res > TKDE_MSPA_DATA/log/NY-d_6_6_bet.log &

nohup ./MSPA.out TKDE_MSPA_DATA/graphs/NY-d/NY-d.index TKDE_MSPA_DATA/graphs/NY-d/NY-d.gr 9  TKDE_MSPA_DATA/queryfile/NY-d_9.Q  5        6     TKDE_MSPA_DATA/candidates/NY-d_6_pcp.cand TKDE_MSPA_DATA/result/NY-d_9_pcp.Res > TKDE_MSPA_DATA/log/NY-d_9_6_pcp.log &
nohup ./MSPA.out TKDE_MSPA_DATA/graphs/NY-d/NY-d.index TKDE_MSPA_DATA/graphs/NY-d/NY-d.gr 8  TKDE_MSPA_DATA/queryfile/NY-d_8.Q  5        6     TKDE_MSPA_DATA/candidates/NY-d_7_pcp.cand TKDE_MSPA_DATA/result/NY-d_8_pcp.Res > TKDE_MSPA_DATA/log/NY-d_8_6_pcp.log &
nohup ./MSPA.out TKDE_MSPA_DATA/graphs/NY-d/NY-d.index TKDE_MSPA_DATA/graphs/NY-d/NY-d.gr 7  TKDE_MSPA_DATA/queryfile/NY-d_7.Q  5        6     TKDE_MSPA_DATA/candidates/NY-d_8_pcp.cand TKDE_MSPA_DATA/result/NY-d_7_pcp.Res > TKDE_MSPA_DATA/log/NY-d_7_6_pcp.log &
nohup ./MSPA.out TKDE_MSPA_DATA/graphs/NY-d/NY-d.index TKDE_MSPA_DATA/graphs/NY-d/NY-d.gr 6  TKDE_MSPA_DATA/queryfile/NY-d_6.Q  5        6     TKDE_MSPA_DATA/candidates/NY-d_9_pcp.cand TKDE_MSPA_DATA/result/NY-d_6_pcp.Res > TKDE_MSPA_DATA/log/NY-d_6_6_pcp.log &

nohup ./MSPA.out TKDE_MSPA_DATA/graphs/NY-d/NY-d.index TKDE_MSPA_DATA/graphs/NY-d/NY-d.gr 9  TKDE_MSPA_DATA/queryfile/NY-d_9.Q  5        6     TKDE_MSPA_DATA/candidates/NY-d_6_mst.cand TKDE_MSPA_DATA/result/NY-d_9_mst.Res > TKDE_MSPA_DATA/log/NY-d_9_6_mst.log &
nohup ./MSPA.out TKDE_MSPA_DATA/graphs/NY-d/NY-d.index TKDE_MSPA_DATA/graphs/NY-d/NY-d.gr 8  TKDE_MSPA_DATA/queryfile/NY-d_8.Q  5        6     TKDE_MSPA_DATA/candidates/NY-d_7_mst.cand TKDE_MSPA_DATA/result/NY-d_8_mst.Res > TKDE_MSPA_DATA/log/NY-d_8_6_mst.log &
nohup ./MSPA.out TKDE_MSPA_DATA/graphs/NY-d/NY-d.index TKDE_MSPA_DATA/graphs/NY-d/NY-d.gr 7  TKDE_MSPA_DATA/queryfile/NY-d_7.Q  5        6     TKDE_MSPA_DATA/candidates/NY-d_8_mst.cand TKDE_MSPA_DATA/result/NY-d_7_mst.Res > TKDE_MSPA_DATA/log/NY-d_7_6_mst.log &
nohup ./MSPA.out TKDE_MSPA_DATA/graphs/NY-d/NY-d.index TKDE_MSPA_DATA/graphs/NY-d/NY-d.gr 6  TKDE_MSPA_DATA/queryfile/NY-d_6.Q  5        6     TKDE_MSPA_DATA/candidates/NY-d_9_mst.cand TKDE_MSPA_DATA/result/NY-d_6_mst.Res > TKDE_MSPA_DATA/log/NY-d_6_6_mst.log &